#! /bin/sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config click_to_focus       true

for m in $(bspc query -M); do
    bspc monitor $m -d eins zwei drei vier fünf sechs sieben acht neun zhen
    bspc config -m $m top_padding 40
done
