#! /bin/sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding     30
bspc config border_width         2
bspc config window_gap          15

bspc monitor DP1 -d eins zwei drei vier fünf sechs sieben
bspc monitor eDP1 -d acht neun zhen

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

for m in $(bspc query -M); do
    bspc config -m $m top_padding 45;
done
