#! /bin/sh

#   **********************
#   wm independent hotkeys
#   ----------------------

#   terminal emulator

super + Return
    urxvt

#    window switcher

super + space
    rofi -show window -terminal urxvt

#    program launcher

super + p
    rofi -show run -terminal urxvt

#   make sxhkd reload its configuration files

super + Escape
    pkill -USR1 -x 'sxhkd -c /home/laika/Environement/runcoms/sxhkdrc' & ~/Environement/runcoms/bspwmrc

#   backlight control

XF86MonBrightnessDown
    xbacklight -dec 5

XF86MonBrightnessUp
    xbacklight -inc 5

super + period
    setxkbmap -layout ru

super + comma
    setxkbmap -layout us -variant intl

#   **********************
#   general bspwm hotkeys
#   ----------------------

#   quit bspwm normally

super + alt + Escape
    bspc quit

#   switch between the tiled and monocle layout

super + m
    bspc desktop -l next

#   close node

super + w
    bspc node -c

#   **********************
#   working with windows/nodes
#   ----------------------

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#
# focus/swap
#

super + backslash
    bspc node next.local -f

super + {minus,equal}
    bspc node {prev,next} -f


# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# focus the next/previous desktop
super + bracket{left,right}
    bspc desktop -f {prev,next}

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

#
# resize tiled/floating
#

# expand the tiled space in the given direction
super + alt + {h,j,k,l}
    bspc node {@west -r -10,@south -r +10,@north -r -10,@east -r +10}

# contract the tiled space in the given direction
super + alt + shift + {h,j,k,l}
    bspc node {@east -r -10,@north -r +10,@south -r -10,@west -r +10}

#
# pointer focus/move/resize
#

# focus
~button1
    bspc pointer -g focus

# start move/resize
super + button{2,3}
    ; bspc pointer -g {move,resize_corner}

# end move/resize
super + @button{2,3}
    bspc pointer -u


