#! /bin/sh

# Disable right click area on Trackpad.
synclient RightButtonAreaLeft=5400 &

# Set keyboard map for US International.
setxkbmap -layout us -variant intl &

# Set a beautiful and big cursor
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 32 &

# Set the X root window background color to default black
# i used hsetroot because xsetroot is buggy with compton
hsetroot -solid black &

# Load PCManFM daemon, for automounting
pcmanfm -d &

# Compositing manager
compton -b &

# Load shortcuts
sxhkd -c ~/Environement/runcoms/sxhkdrc &

# Load Window Manager
exec bspwm -c ~/Environement/runcoms/bspwmrc
