#!/bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=40
PANEL_FONT='xft:Hack:size=12'
PANEL_ICONS='FontAwesome:size=16'
PANEL_WM_NAME=bspwm_panel
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT PANEL_WM_NAME

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then

    exit 1
fi

. ~/Environement/scripts/panel/panel_colors

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
echo -e 'T '$USER'@'$HOST > "$PANEL_FIFO" &

. ~/Environement/scripts/panel/widgets/clock &

~/Environement/scripts/panel/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
   sleep 0.05
   wid=$(xdo id -a "$PANEL_WM_NAME")
   tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
